spring:
  security:
    oauth2:
      client:
        registration:
          casdoor:
            client-id: ${CASDOOR_CLIENT_ID}
            client-secret: ${CASDOOR_CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          casdoor:
            issuer-uri: ${CASDOOR_ISSUER_URI:}
vola:
  admins: ${VOLA_ADMINS}
