name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

  workflow_call:



jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      AWS_REGION: eu-west-3
      ORANGE_API_URL: ${{
              (github.event_name == 'pull_request' && github.base_ref == 'prod') && secrets.PROD_ORANGE_API_URL ||
              (github.event_name == 'pull_request' && github.base_ref == 'preprod') && secrets.PREPROD_ORANGE_API_URL ||
              (github.ref == 'refs/heads/prod') && secrets.PROD_ORANGE_API_URL ||
              (github.ref == 'refs/heads/preprod') && secrets.PREPROD_ORANGE_API_URL
              }}
      SPRING_SESSION_JDBC_INITIALIZE_SCHEMA: ${{
              (github.event_name == 'pull_request' && github.base_ref == 'prod') && secrets.PROD_SPRING_SESSION_JDBC_INITIALIZE_SCHEMA ||
              (github.event_name == 'pull_request' && github.base_ref == 'preprod') && secrets.PREPROD_SPRING_SESSION_JDBC_INITIALIZE_SCHEMA ||
              (github.ref == 'refs/heads/prod') && secrets.PROD_SPRING_SESSION_JDBC_INITIALIZE_SCHEMA ||
              (github.ref == 'refs/heads/preprod') && secrets.PREPROD_SPRING_SESSION_JDBC_INITIALIZE_SCHEMA
              }}
      SPRING_SESSION_STORETYPE: ${{
              (github.event_name == 'pull_request' && github.base_ref == 'prod') && secrets.PROD_SPRING_SESSION_STORETYPE ||
              (github.event_name == 'pull_request' && github.base_ref == 'preprod') && secrets.PREPROD_SPRING_SESSION_STORETYPE ||
              (github.ref == 'refs/heads/prod') && secrets.PROD_SPRING_SESSION_STORETYPE ||
              (github.ref == 'refs/heads/preprod') && secrets.PREPROD_SPRING_SESSION_STORETYPE
              }}
      SPRING_FLYWAY_OUTOFORDER: ${{
              (github.event_name == 'pull_request' && github.base_ref == 'prod') && secrets.PROD_SPRING_FLYWAY_OUTOFORDER ||
              (github.event_name == 'pull_request' && github.base_ref == 'preprod') && secrets.PREPROD_SPRING_FLYWAY_OUTOFORDER ||
              (github.ref == 'refs/heads/prod') && secrets.PROD_SPRING_FLYWAY_OUTOFORDER ||
              (github.ref == 'refs/heads/preprod') && secrets.PREPROD_SPRING_FLYWAY_OUTOFORDER
              }}


    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: chmod +x .shell/publish_gen_to_maven_local.sh
      - run: |
          ./gradlew test \
            -Dorange.api.url="$ORANGE_API_URL" \
            -Dspring.session.jdbc.initialize.schema="$SPRING_SESSION_JDBC_INITIALIZE_SCHEMA" \
            -Dspring.session.storetype="$SPRING_SESSION_STORETYPE" \
            -Dspring.flyway.outoforder="$SPRING_FLYWAY_OUTOFORDER"

      

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code